### ISSUE TITLE
Roadmap for v0.0.1

### ISSUE THREAD

**Issue by zoccoler** [napari-phasors/napari-phasors#16]
- [x] Reader plugin that support reading raw data from the following file formats (#2) :
  - [x] `.lsm`
  - [x] `.ptu`
  - [x] `.sdt`
  - [x] `.tif`
  - [x] `ome-tif`
- [x] Reader that reads processed data (#2) :
  - [x] `.ome-tif`  
- [x] Widget that reads and calculate phasors from raw data files offering more options (like more harmonics, etc) (#2)
- [x] Writer plugin that saves data as `.ome-tif`
- [x] Make a Plotter widget
  - [x] Plot phasors as 2D histogram
  - [x] Select data from plot and visualize results back in viewer as new layers
    - [x] Free-hand
    - [x] Circle selection (holding SHIFT should ensure perfect circle)
    - [x] Colors in log scale
- [x] Widget for thresholding average image (like in Fiji) (#18)
- [x] Widget to apply median filter to G and S images (with variable kernel size and number of iterations)
- [x] Widget for FLIM calibration (#7)
- [x] Add sample files (#3)
- [x] Fix aspect ratio of plotter
- [x] Export `.csv` table with phasor coordinates (#55)
- [x] Colormap the image according to apparent lifetime (#54)
- [x] Write documentation
- [x] Write unit tests

**Comment by zoccoler** [comment]
Solved after #71
